import Header from './components/Header';
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  // this is global meta data for the entire application. You would need to import the metadata component into each other page to have their own metadata
  title: 'Next 13 | Newest Updates',
  description: 'Generated by create next app',
  // keywords go here as well
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Header />
        <main className='container'>{children}</main>
      </body>
    </html>
  );
}
